spring: 
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev		#测试环境
  application:
    name: microservicecloud-config-sweet-dev
---
spring: 
  profiles: test	#测试环境
  application:
    name: microservicecloud-config-sweet-test
#  请保存为utf-8格式