spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept                          # 对外暴露的微服务的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/microservicecloud
    username: root
    password: 1215
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最小维持连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatiscfg.xml
  type-aliases-package: com.sweet.springcloud.pojo        # 所有pojo别名所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件所在的位置

eureka:
  client:            #  客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001               # 自定义服务器名称信息
    prefer-ip-address: true                               # 访问路径可以显示ip地址

info:
  app.name: sweet-microservicecloud
  company.name: www.sweet.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-dept                          # 对外暴露的微服务的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/microservicecloud2
    username: root
    password: 1215
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最小维持连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatiscfg.xml
  type-aliases-package: com.sweet.springcloud.pojo        # 所有pojo别名所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     # mapper映射文件所在的位置

eureka:
  client:            #  客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001               # 自定义服务器名称信息
    prefer-ip-address: true                               # 访问路径可以显示ip地址

info:
  app.name: sweet-microservicecloud
  company.name: www.sweet.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$